### ISSUE TITLE
PACKAGED service : new licence packs based on Nutanix Cloud Platform 2.0 portfolio

### ISSUE THREAD

**Issue by Hubmar** [ovh/private-cloud-roadmap#120]
In Feb 2022, Nutanix updated their licence packs with new bundle based on 
- Nutanix Cloud Infrastructure (AOS, AHV, Karbon, Flow NW) + Flow Mseg
- Nutanix Cloud Manager (Calm, Beam, Security Central, Prism)

https://www.nutanix.com/blog/solving-hybrid-multicloud-complexity

As a customer I want to be able to choose within OVHcloud a pack matching the Nutanix's ones 
so that
my experience on OVHcloud is similar to my on-prem experience  or within another cloud provider

**Comment by mlt-ovh** [comment]
New Nutanix on OVHcloud Packaged Service available.
https://www.ovhcloud.com/en-ie/hosted-private-cloud/nutanix/packaged/

US availability coming soon.

**Comment by mlt-ovh** [comment]
New Nutanix on OVHcloud Packaged Service available in the US too.
