### ISSUE TITLE
Beta : Nutanix clusters in RBX

### ISSUE THREAD

**Issue by baaastijn** [ovh/private-cloud-roadmap#32]
THIS ISSUE IS FOR THE BETA PHASE ONLY

**User story**

As a customer,
I want to test and deploy preinstalled Nutanix clusters in RBX datacenter 
So that
I can valide my workflow and use case in a practical environment

**Beta Request**

Contact our sales teams via email, phone or via https://www.ovhcloud.com/fr/lp/nutanix/ 

**Acceptance criterias**
- Nutanix cluster delivered in less that 48h
- Credentials received via email
- Ability to connect to Nutanix Prism Pro UI
- Ability to move the cluster in a private network (vRack), and attach IP ranges

**BETA phase limitations**
- Free during the whole beta phase (2 month par cluster)
- Limited range of nodes
- No OVHcloud control panel
- Not ready for production
- SLA for the hardware only, not the software
- Support for the hardware only, not the software

**Comment by mlt-ovh** [comment]
Nutanix on OVHcloud is live in RBX.
