### ISSUE TITLE
General Availability RBX/GRA/BHS - Milestone 1

### ISSUE THREAD

**Issue by baaastijn** [ovh/private-cloud-roadmap#35]
**User story**

As a customer,
I want deploy and use for production preinstalled Nutanix clusters in RBX or BHS datacenter 
So that
I can host my workloads easily in the cloud with flexibility, security, and easiness. All of that with Enterprise SLA and support

**Acceptance criterias**
- Nutanix cluster delivered in few hours
- Nutanix Licences : AOS Pro or AOS Ultimate, and each time Prism Pro and Flow 
- Credentials received via email
- Ability to connect to Nutanix Prism Pro UI
- Ability to move the cluster in a private network (vRack), and attach IP ranges
- (new vs BETA) Control panel available
- (new vs BETA) OFficial contract with SLA
- (new vs BETA) Official support

**MILESTONE 1 limitations**
- Limited range of nodes : HCI-1 only
- Limited Datacenters : RBX, GRA and BHS
- You cannot bring you own licences or add another licences (VDI, Databases, ...)
- no order funnel in the website. Order via Sales teams only.
- Add/Remove nodes : only via Sales teams, not via customer 
- Redeploy : via API only

**Comment by mlt-ovh** [comment]
Nutanix on OVHcloud is live in RBX / GRA / BHS
