### ISSUE TITLE
Entry level hosts based on SCALE range

### ISSUE THREAD

**Issue by baaastijn** [ovh/private-cloud-roadmap#38]
**User Story**
As a customer i want the *latest* SCALE range for the nodes hardware
so that
I'm able to get more affordable configurations

**Acceptance criterias
- ability to deploy a new cluster with SCALE
- nodes based on SCALE range : https://www.ovhcloud.com/fr/bare-metal/scale/
- Less expensive VS HG range

**Comment by mlt-ovh** [comment]
SCALE server range is now nutanix qualified and available for sale on ovhcloud.com
