### ISSUE TITLE
Backup your Nutanix cluster with HYCU

### ISSUE THREAD

**Issue by raph-a-l** [ovh/private-cloud-roadmap#66]
User Story
As a customer i want to backup my Hosted Private Cloud powered by Nutanix cluster  with HYCU 
so that
I benefit from additional data protection by leveraging on a seamless solution offering state of the art backup solution: HYCU.

Link to user guide: https://docs.ovh.com/ie/en/nutanix/hycu-backup/

**Comment by mlt-ovh** [comment]
Feature tracked here : 
https://github.com/ovh/private-cloud-roadmap/issues/76
