### ISSUE TITLE
Backup my Nutanix cluster with HYCU solution

### ISSUE THREAD

**Issue by raph-a-l** [ovh/private-cloud-roadmap#76]
As a customer I want to leverage seamless backup solution for my Nutanix cluster to benefit from increased uptime & reduced data loss.

HYCU simplifies your data protection strategy with a unified platform to backup, migrate, and recover everything from applications to VMs to containers.

**Comment by mlt-ovh** [comment]
HYCU for OVHcloud is live : https://www.ovhcloud.com/en-gb/storage-solutions/hycu/
